#!/usr/bin/env python3
"""Parse voting.csv and generate voting_data.js for the Insitorian front page."""

import csv
import json
import re
from datetime import datetime, timedelta, timezone

PLANETS = ["Promitor", "Avalon", "Boucher"]

STARTS = {
    "Promitor": datetime(2026, 2, 12, 20, 0, tzinfo=timezone.utc),
    "Avalon": datetime(2026, 2, 12, 20, 0, tzinfo=timezone.utc),
    "Boucher": datetime(2026, 2, 16, 20, 0, tzinfo=timezone.utc),
}

DURATION = timedelta(days=7)


def clean_name(name):
    """Strip '--' markers and title-case all-caps names."""
    name = name.strip("-")
    if name.isupper():
        return name.title()
    return name


def parse_cell(cell_text):
    """Parse a vote-data cell into {candidate: votes} dict."""
    results = {}
    if not cell_text or not cell_text.strip():
        return results
    for line in cell_text.strip().split("\n"):
        parts = line.split("\t")
        if len(parts) < 2:
            parts = re.split(r"  +", line.strip())
        if len(parts) >= 2:
            results[clean_name(parts[1])] = int(parts[0])
    return results


def main():
    with open("voting.csv", newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))

    timestamps = []
    for ts_str in rows[0][1:]:
        ts_str = ts_str.strip()
        if ts_str:
            timestamps.append(
                datetime.strptime(ts_str, "%Y-%m-%d %H:%M").replace(
                    tzinfo=timezone.utc
                )
            )

    planet_data = {}
    for row in rows[1:]:
        planet = row[0].strip()
        if planet not in PLANETS:
            continue

        snapshots = [parse_cell(cell) for cell in row[1:]]
        all_candidates = set()
        for snap in snapshots:
            all_candidates.update(snap.keys())

        start = STARTS[planet]
        end = start + DURATION
        started = len(timestamps) > 0 and timestamps[-1] >= start

        series = []
        for candidate in all_candidates:
            points = []
            for i, snap in enumerate(snapshots):
                if i < len(timestamps):
                    hours = (timestamps[i] - start).total_seconds() / 3600
                    if hours < 0:
                        continue
                    points.append([round(hours, 2), snap.get(candidate, 0)])
            series.append({"name": candidate, "data": points})

        series.sort(
            key=lambda s: s["data"][-1][1] if s["data"] else 0, reverse=True
        )

        planet_data[planet.lower()] = {
            "start": start.strftime("%Y-%m-%dT%H:%MZ"),
            "end": end.strftime("%Y-%m-%dT%H:%MZ"),
            "started": started,
            "series": series,
        }

    latest = timestamps[-1].strftime("%Y-%m-%dT%H:%MZ") if timestamps else "unknown"
    js = (
        "// Generated by parse_votes.py from data up to "
        + latest
        + "\n"
        + "var votingData = "
        + json.dumps(planet_data, indent=2)
        + ";\n"
    )

    with open("voting_data.js", "w") as f:
        f.write(js)

    for name, pd in planet_data.items():
        n = len(pd["series"])
        pts = len(pd["series"][0]["data"]) if pd["series"] else 0
        status = "active" if pd["started"] else "not started"
        print(f"  {name}: {n} candidates, {pts} data points ({status})")

    print("Written to voting_data.js")


if __name__ == "__main__":
    main()
